# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build CKEditor
        run: |
          cd src/libs/ckeditor5
          npm install
          npm run build

      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          APP_NAME: "PWA Dashboard"
          APP_DESCRIPTION: "A dashboard. That's it."

          # App Settings
          CORS_PROXY_PORT: 8080
          KIMAI_FRIENDLY_URL: ${{ secrets.KIMAI_FRIENDLY_URL }}
          KIMAI_BASE_URL: ${{ secrets.KIMAI_BASE_URL }}
          KIMAI_USER: ${{ secrets.KIMAI_USER }}
          KIMAI_KEY: ${{ secrets.KIMAI_KEY }}
          SERVER_JWT_SECRET: ${{ secrets.SERVER_JWT_SECRET }}
          SERVER_AUTH_PASSWORD: ${{ secrets.SERVER_AUTH_PASSWORD }}

          # PAWCONFIG
          PORT: 3003
          HOST: 0.0.0.0
          APP_ROOT_URL: "/"
          CDN_URL: ""
          SSR_ENABLED: true
          SERVICE_WORKER_ENABLED: true
          SINGLE_PAGE_APPLICATION: false
          USE_HASHED_ROUTES: false
          ASYNC_CSS: true
          POLYFILL_CDN: false
          REACT_CDN: false
          CLIENT_ROOT_ELEMENT_ID: "app"
          HSTS_ENABLED: true
          HSTS_MAX_AGE: 31536000
          ASSETS_MAX_AGE: 2592000000
          HSTS_INCLUDE_SUBDOMAINS: false
          HSTS_PRELOAD: false
          DISABLE_JS: false
          DISABLE_CACHE: true
        run: npm run build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Source directory
          SOURCE: dist/
          # Target directory
          TARGET: /var/www/pwa-dashboard
